[2023-06-25 23:03:58,919: INFO: stage__04__train]: 
********************
[2023-06-25 23:03:58,919: INFO: stage__04__train]: >>>>> stage TEMPLATE started <<<<<
[2023-06-25 23:03:58,921: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-06-25 23:03:58,921: INFO: stage__04__train]: read the data from data/PetImages
[2023-06-25 23:03:58,921: ERROR: stage__04__train]: 'image_size'
Traceback (most recent call last):
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/src/stage__04__train.py", line 82, in <module>
    main(config_path=parsed_args.config)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/src/stage__04__train.py", line 35, in main
    image_size = params["image_size"],
KeyError: 'image_size'
[2023-06-25 23:05:27,841: INFO: stage__04__train]: 
********************
[2023-06-25 23:05:27,841: INFO: stage__04__train]: >>>>> stage TEMPLATE started <<<<<
[2023-06-25 23:05:27,842: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-06-25 23:05:27,842: INFO: stage__04__train]: read the data from data/PetImages
[2023-06-25 23:05:28,469: ERROR: stage__04__train]: 'size' must be a 1-D Tensor of 2 elements: new_height, new_width
Traceback (most recent call last):
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/src/stage__04__train.py", line 82, in <module>
    main(config_path=parsed_args.config)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/src/stage__04__train.py", line 30, in main
    train_ds = tf.keras.preprocessing.image_dataset_from_directory(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 302, in image_dataset_from_directory
    dataset = paths_and_labels_to_dataset(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 343, in paths_and_labels_to_dataset
    img_ds = path_ds.map(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2240, in map
    return map_op._map_v2(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/map_op.py", line 40, in _map_v2
    return _ParallelMapDataset(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/map_op.py", line 148, in __init__
    self._map_func = structured_function.StructuredFunctionWrapper(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 261, in __init__
    self._function = fn_factory()
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 232, in get_concrete_function
    concrete_function = self._get_concrete_function_garbage_collected(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 202, in _get_concrete_function_garbage_collected
    concrete_function, _ = self._maybe_define_concrete_function(args, kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 166, in _maybe_define_concrete_function
    return self._maybe_define_function(args, kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 396, in _maybe_define_function
    concrete_function = self._create_concrete_function(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 300, in _create_concrete_function
    func_graph_module.func_graph_from_py_func(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1214, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 238, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 169, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 344, in <lambda>
    lambda x: load_image(x, *args), num_parallel_calls=tf.data.AUTOTUNE
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 367, in load_image
    img = tf.image.resize(img, image_size, method=interpolation)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/ops/image_ops_impl.py", line 1459, in _resize_images_common
    raise ValueError('\'size\' must be a 1-D Tensor of 2 elements: '
ValueError: 'size' must be a 1-D Tensor of 2 elements: new_height, new_width
[2023-06-25 23:07:06,240: INFO: stage__04__train]: 
********************
[2023-06-25 23:07:06,240: INFO: stage__04__train]: >>>>> stage TEMPLATE started <<<<<
[2023-06-25 23:07:06,242: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-06-25 23:07:06,242: INFO: stage__04__train]: read the data from data/PetImages
[2023-06-25 23:07:06,859: ERROR: stage__04__train]: 'size' must be a 1-D Tensor of 2 elements: new_height, new_width
Traceback (most recent call last):
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/src/stage__04__train.py", line 82, in <module>
    main(config_path=parsed_args.config)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/src/stage__04__train.py", line 30, in main
    train_ds = tf.keras.preprocessing.image_dataset_from_directory(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 302, in image_dataset_from_directory
    dataset = paths_and_labels_to_dataset(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 343, in paths_and_labels_to_dataset
    img_ds = path_ds.map(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2240, in map
    return map_op._map_v2(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/map_op.py", line 40, in _map_v2
    return _ParallelMapDataset(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/map_op.py", line 148, in __init__
    self._map_func = structured_function.StructuredFunctionWrapper(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 261, in __init__
    self._function = fn_factory()
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 232, in get_concrete_function
    concrete_function = self._get_concrete_function_garbage_collected(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 202, in _get_concrete_function_garbage_collected
    concrete_function, _ = self._maybe_define_concrete_function(args, kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 166, in _maybe_define_concrete_function
    return self._maybe_define_function(args, kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 396, in _maybe_define_function
    concrete_function = self._create_concrete_function(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 300, in _create_concrete_function
    func_graph_module.func_graph_from_py_func(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1214, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 238, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 169, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 344, in <lambda>
    lambda x: load_image(x, *args), num_parallel_calls=tf.data.AUTOTUNE
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 367, in load_image
    img = tf.image.resize(img, image_size, method=interpolation)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/ops/image_ops_impl.py", line 1459, in _resize_images_common
    raise ValueError('\'size\' must be a 1-D Tensor of 2 elements: '
ValueError: 'size' must be a 1-D Tensor of 2 elements: new_height, new_width
[2023-06-25 23:11:42,035: INFO: stage__04__train]: 
********************
[2023-06-25 23:11:42,035: INFO: stage__04__train]: >>>>> stage TEMPLATE started <<<<<
[2023-06-25 23:11:42,037: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-06-25 23:11:42,037: INFO: stage__04__train]: read the data from data/PetImages
[2023-06-25 23:11:42,663: ERROR: stage__04__train]: 'size' must be a 1-D Tensor of 2 elements: new_height, new_width
Traceback (most recent call last):
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/src/stage__04__train.py", line 82, in <module>
    main(config_path=parsed_args.config)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/src/stage__04__train.py", line 30, in main
    train_ds = tf.keras.preprocessing.image_dataset_from_directory(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 302, in image_dataset_from_directory
    dataset = paths_and_labels_to_dataset(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 343, in paths_and_labels_to_dataset
    img_ds = path_ds.map(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2240, in map
    return map_op._map_v2(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/map_op.py", line 40, in _map_v2
    return _ParallelMapDataset(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/map_op.py", line 148, in __init__
    self._map_func = structured_function.StructuredFunctionWrapper(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 261, in __init__
    self._function = fn_factory()
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 232, in get_concrete_function
    concrete_function = self._get_concrete_function_garbage_collected(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 202, in _get_concrete_function_garbage_collected
    concrete_function, _ = self._maybe_define_concrete_function(args, kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 166, in _maybe_define_concrete_function
    return self._maybe_define_function(args, kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 396, in _maybe_define_function
    concrete_function = self._create_concrete_function(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 300, in _create_concrete_function
    func_graph_module.func_graph_from_py_func(
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1214, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 238, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/data/ops/structured_function.py", line 169, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/autograph/impl/api.py", line 458, in _call_unconverted
    return f(*args, **kwargs)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 344, in <lambda>
    lambda x: load_image(x, *args), num_parallel_calls=tf.data.AUTOTUNE
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/keras/utils/image_dataset.py", line 367, in load_image
    img = tf.image.resize(img, image_size, method=interpolation)
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/joti/Documents/DL/ML_Flow/cnn-app21.6.23/MLflow-CNN-app/env/lib/python3.10/site-packages/tensorflow/python/ops/image_ops_impl.py", line 1459, in _resize_images_common
    raise ValueError('\'size\' must be a 1-D Tensor of 2 elements: '
ValueError: 'size' must be a 1-D Tensor of 2 elements: new_height, new_width
[2023-06-25 23:15:10,747: INFO: stage__04__train]: 
********************
[2023-06-25 23:15:10,748: INFO: stage__04__train]: >>>>> stage TEMPLATE started <<<<<
[2023-06-25 23:15:10,749: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2023-06-25 23:15:10,749: INFO: stage__04__train]: read the data from data/PetImages
[2023-06-25 23:15:11,996: INFO: stage__04__train]: load the base model from {path_to_model}
[2023-06-25 23:15:11,996: INFO: stage__04__train]: start training
